#!/usr/bin/env bash
#
# Query que cambia la fecha del formato utilizado en GECI a formato ISO8601
data_file=${1}
export table_name=$(basename "$data_file" .csv)
export column_name=${2:-Fecha}
query=$(envsubst < /usr/local/bin/query_cambia_formato_fecha.sql)
csvsql --snifflimit 0 --no-inference --blanks --query "${query}" ${data_file} \
  | csvcut --not-columns ${column_name} \
  | sed s/Fecha_ISO8601/${column_name}/g
