#!/usr/bin/env bash
#
# Query que cambia la fecha del formato utilizado en GECI a formato ISO8601
case "$1" in
  -h | --help) cat /usr/local/doctests/test_${0##*/}.py | head --lines=-1 | tail --lines=+2 && exit 0 ;;
esac


data_file=${1}
export table_name=$(basename "${data_file}" .csv)
export column_name=${2:-Fecha}
src_path=$(dirname "${0}")
query=$(envsubst < ${src_path}/query_cambia_formato_fecha.sql)
csvsql --snifflimit 0 --no-inference --blanks --query "${query}" ${data_file} \
  | csvcut --not-columns ${column_name} \
  | sed s/Fecha_ISO8601/${column_name}/g
