#!/usr/bin/env bash
#
# ./src/cat_lat_and_lon_files alacranes
poligono=${1}
isla=${2}
{ echo -e "lat,lon"; } > ${isla}_lat_lon_file.csv
./src/create_lat_and_lon_data_file ${poligono} ${isla}
pr -mts, ${isla}_lat_coordinates.csv ${isla}_lon_coordinates.csv >> ${isla}_lat_lon_file.csv
