#!/usr/bin/env bash
#
#Función para contar capturas de gatos y esfuerzo en tabla posicion_trampas por zona y por año.
first_file=${1}
first_table=$(basename "${first_file}" .csv)
csvsql --snifflimit 0 --no-inference --blanks --query \
"SELECT
  strftime('%Y',Fecha) AS Temporada,
  CASE 
    WHEN ID_de_trampa = 'NA' THEN 'NA'
    WHEN ID_de_trampa = 'SM4-Melpo' THEN '01'
    ELSE SUBSTR(ID_de_trampa,4,2)
  END Zona,
  COUNT(*) AS Capturas
FROM ${first_table}
WHERE Estado_trampa = 'X'
GROUP BY Temporada, Zona
" ${first_file} > Capturas.csv;

csvsql --snifflimit 0 --no-inference --blanks --query \
"SELECT
  strftime('%Y',Fecha) AS Temporada,
  CASE 
    WHEN ID_de_trampa = 'NA' THEN 'NA'
    WHEN ID_de_trampa = 'SM4-Melpo' THEN '01'
    ELSE SUBSTR(ID_de_trampa,4,2)
  END Zona,
  COUNT(*) AS Esfuerzo
FROM ${first_table}
WHERE Estado_trampa = 'X' OR Estado_trampa = 'A'
GROUP BY Temporada, Zona
" ${first_file} > Esfuerzos.csv;

csvsql --snifflimit 0 --no-inference --blanks --query \
"SELECT E.Temporada,E.Zona,E.Esfuerzo, C.Capturas
FROM Esfuerzos AS E
LEFT OUTER JOIN Capturas AS C
ON E.Temporada = C.Temporada AND E.Zona = C.Zona
" Capturas.csv Esfuerzos.csv;