#!/usr/bin/env bash
#
# ./src/create_lat_and_lon_data_file socorro
poligono=${1}
isla=${2}
for coordinate in lat lon; do
  ./src/select_coordinates_by_island ${poligono} ${isla} \
  | jq '.[].'${coordinate}'[]' > ${isla}_${coordinate}_coordinates.csv
done
