#!/usr/bin/env bash
#
data_file=${1}
path_file=$(dirname ${data_file})
name_file=$(basename ${data_file} .csv)
./src/change_header ${data_file} > ${path_file}/${name_file}_tmp_header.csv
./src/get_captures_by_zone ${path_file}/${name_file}_tmp_header.csv > ${path_file}/captures_${name_file}.csv
./src/get_effort_by_zone ${path_file}/${name_file}_tmp_header.csv > ${path_file}/effort_${name_file}.csv
./src/remove_rows_with_specific_text ${path_file}/captures_${name_file}.csv
./src/remove_rows_with_specific_text ${path_file}/effort_${name_file}.csv
