#!/usr/bin/env bash
#
data_file=${1}
path_file=$(dirname ${data_file})
name_file=$(basename ${data_file} .csv)
captures_file="${path_file}/captures_${name_file}.csv"
effort_file="${path_file}/effort_${name_file}.csv"
weekly_resume="${path_file}/weekly_resume_${name_file}.csv"
data_file_tmp_header="${path_file}/${name_file}_tmp_header.csv"

./src/change_header ${data_file} > ${data_file_tmp_header}
./src/get_captures_by_zone ${data_file_tmp_header} > ${captures_file}
./src/get_effort_by_zone ${data_file_tmp_header} > ${effort_file}
./src/remove_rows_with_specific_text ${captures_file}
./src/remove_rows_with_specific_text ${effort_file}
./src/join_effort_and_captures_files ${effort_file} ${captures_file} > ${weekly_resume}
sed -e "s/,$/,0/" ${weekly_resume}
