#!/usr/bin/env bash
#
#
for fecha in Fecha_1 Fecha_2 Fecha_3 Fecha_4 Fecha_5 Fecha_6 Fecha_7; do
  file_name=${1}
  table_name=$(basename "${file_name}" .csv)
  csvsql --snifflimit 0 --no-inference --blanks --query \
  "SELECT
  '${fecha}' AS Fecha,
    CASE 
      WHEN ID = 'NA' THEN 'NA'
      WHEN ID = 'SM4-Melpo' THEN '01'
      ELSE SUBSTR(ID,4,2)
    END Zona,
    COUNT(${fecha}) AS Capturas
  FROM ${table_name}
  WHERE ${fecha} = 'X'
  GROUP BY Zona
  " ${file_name}
done
