#!/usr/bin/env bash
#
#
first_file=${1}
first_table=$(basename "${first_file}" .csv)
csvsql --snifflimit 0 --no-inference --blanks --query \
"SELECT
  strftime('%Y',Fecha) AS Temporada,
  CASE 
    WHEN ID_de_trampa = 'NA' THEN 'NA'
    WHEN ID_de_trampa = 'SM4-Melpo' THEN '01'
    ELSE SUBSTR(ID_de_trampa,4,2)
  END Zona,
  COUNT(*) AS Capturas
FROM ${first_table}
WHERE Estado_trampa = 'X'
GROUP BY Temporada, Zona
" ${first_file} > Capturas.csv;