#!/usr/bin/env bash
#
#
effort_name_file=${1}
captures_name_file=${2}
effort_table=$(basename "${effort_name_file}" .csv)
captures_table=$(basename "${captures_name_file}" .csv)
csvsql --snifflimit 0 --no-inference --blanks --query "
SELECT
  e.Fecha,
  e.Zona,
  e.Esfuerzo,
  c.Capturas
FROM ${effort_table} AS e
LEFT OUTER JOIN ${captures_table} AS c
ON e.Fecha = c.Fecha AND e.Zona = c.Zona
" ${effort_name_file} ${captures_name_file}
