#!/usr/bin/env bash
#
# Selecciona las coordenadas del poligono de una isla.
# ./src/select_coordinates_by_island tests/data/poligonos.json socorro
poligono=${1}
isla=${2}
latitud_isla=$(cat $poligono | jq '.[]
  | select(.id == "'${isla}'")
  | {"Geopoligono"}')
echo ${latitud_isla}
